### ISSUE TITLE
License compatible with nixpkgs

### ISSUE THREAD

**Issue by rehno-lindeque** [nixified-ai/flake#33]
Hi,

I was wondering if the AGPL-3.0 license used here is compatible with nixpkgs MIT? 

I'm not sure yet but I had been thinking of potentially submitting one or two packages upstream, would this be permitted?

**Comment by MatthewCroughan** [comment]
If you are referring to invokeai/koboldai directly, I would appreciate improvements to be made to the flake directly, specifically because I think this is more of maintenance burden for Nixpkgs otherwise, given how these programs work (buggy and hard).

If you're referring to the Python derivations in `packages` those definitely need to be upstreamed, and I really hope that happens.

https://opensource.stackexchange.com/questions/7904/can-your-mit-library-use-an-lgpl-library

**Comment by rehno-lindeque** [comment]
I was looking at gradio because it's all that I need right now, but I also just generally wanted to check that it's ok.

Thanks!

**Comment by MatthewCroughan** [comment]
@rehno-lindeque My intent was to have the overlays be MIT licensed so that it is compatible. We may therefore have to make that known by including a LICENSE file at the root of the `packages` folder.

**Comment by MatthewCroughan** [comment]
Done via 5bb40e7b87f0b3098f72bcb66b1fcb409ce19b6a
