### ISSUE TITLE
 cp: not replacing '/var/lib/invokeai/configs/models.yaml'

### ISSUE THREAD

**Issue by IvanMalison** [nixified-ai/flake#46]
When I set up the service I get this error on startup. Perhaps an upstream issue?

**Comment by MatthewCroughan** [comment]
It's an upstream issue, we cannot manage the state transition between one version of InvokeAI to another for them, there's some conversation about this in #40 and I've talked to them in Discord. They don't seem to be getting any better with it, and everyone suffers on major version upgrades. Best setup would be to have Nix fetch everything and just construct the InvokeAI directories, rather than allowing the program to mismanage its state.
